language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test package publishOnlyWhenOnMaster
scala:
  - 2.11.0-RC4
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8
notifications:
  email:
    - eugene.burmako@epfl.ch
    - denys.shabalin@typesafe.com
env:
  global:
   - SCALAREFLECT_MAVEN_REALM="Sonatype Nexus Repository Manager"
   - SCALAREFLECT_MAVEN_DOMAIN="oss.sonatype.org"
   - secure: "OJeJ+4m1uwa+8JjtF+z5bRR9cqpaFvUdpuSmU9SqrBFgd/ZsED/qAi1UUIlIYvewCS0c0S5PtA0zQgkuOmjAg3HCFZxfUx/Zs9HS0HNunJiEnQjllJo/fLYsLo+Fr9iiCBBiXgA38hVXTuOKhMJzS648z8ICq3C1GooGXJVWEdc="
   - secure: "Cqak82DCMqYp72mRwzIyfGkaI00HqWgpjODZXlrv9/9V9Sb/NwIIzPkjNWzQAoiAxj7OksN29/ISax2q2+SzUIbpi+wdPVJ2oKCs4Av28yV9KmjAqlE5gU/ReBaDkbxcSmVEQlSP2F/CMkKw95uJa4JiUNWKcXWC+MmPJbDrIGE="
